### PR TITLE
Fix sending Labels with Brush

### LINKED ISSUE #404: Sending Label with Brush Selection doesn't work
## Current Behavior

Sending Label with Brush Selection doesn't work.

## Expected Behavior

Label with Brush Selection should be sent correctly.

## Steps to Reproduce the Problem

  1. Go to labeling page and use Brush Tool
  2. Send label
  3. "Can't send scan" appeared

### PR DESCRIPTION
**Pull request by jpowie01**
Fixes #404 

## Proposed Changes

  - Use Tag key instead of name,
  - Send Brush images as files instead of base64 (transfer reduction by ~33%),
  - Allow selections to add files/additional data to the final Label.

### CODE REVIEW

File: frontend/src/app/model/selections/SliceSelection.ts [hunk 1]
```diff
@@ -19,4 +19,17 @@ export abstract class SliceSelection {
     }
 
     public abstract toJSON(): Object;
+    public getAdditionalData(): Object {
+        return {};
+    }
+
+    protected static base64toBlob(base64: string, dataType: string = 'image/png'): Blob {
```
Comment (jpowie01) [inline frontend/src/app/model/selections/SliceSelection.ts]: Is there a better place for such functions?

Comment (Darkoon) [reply frontend/src/app/model/selections/SliceSelection.ts]: Well, some service or util will be good. There are few functions that can be then moved there.
