### PR TITLE
Fix loading for Scans with low number of Slices

### LINKED ISSUE #405: Scans with low number of Slices are not properly loaded on Labeling page
## Current Behavior

When Scan has less than 10 Slices, Scan Viewer keeps displaying spinner indicator and never gets to displaying actual Scan.

## Expected Behavior

Scan should be displayed properly, no matter how many Slices it has.

## Steps to Reproduce the Problem

  1. Upload less than 10 Slices.
  2. Go to Labelling page.
  3. Voi'la, Scan is not displayed, instead you're presented with spinner indicator that doesn't dissapear.

## Additional comment (optional)

Reason for that happening is that `SLICE_BATCH_SIZE` (`validation-page.component.ts`, Line 23) is fixed to 10. When we upload Scan that has less than `SLICE_BATCH_SIZE` slices, method `slice.isLastInBatch()` (`marker-page.component.ts`, Line 101) will always return `false`, because it will never hit slice with id = 9 (because there isn't one...). Therefore, Slice download will never be marked as completed.

### PR DESCRIPTION
**Pull request by jszemplinski**
Fixes #405

## Proposed Changes

  - Scans with less than 10 Slices are now properly loaded and displayed. Spinner indicator being stuck is no longer an issue.

### CODE REVIEW

File: frontend/src/app/pages/marker-page/marker-page.component.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ export class MarkerPageComponent implements OnInit {
                 this.lastSliceID = slice.index;
             }
             this.marker.feedData(slice);
-            if (slice.isLastInBatch()) {
+            if (slice.isLastInBatch() || (slice.index === this.scan.numberOfSlices - 1)) {
```
Comment (jpowie01) [inline frontend/src/app/pages/marker-page/marker-page.component.ts]: I think that `isLastInBatch()` should be enough. Otherwise, maybe there is an error on the backend side?

Backend returns information about SliceIndex and indicator which SliceIndex is last in current batch. Checking manually for last Slice in Scan should be redundant.

Comment (jszemplinski) [reply frontend/src/app/pages/marker-page/marker-page.component.ts]: Batch size is fixed to 10 slices (`validation-page.component.ts`, line 23). Therefore, for Scans with <10 Slices, last Slice index is always set to 9. `isLastInBatch()` compares all of the Slices looking for one with id 9, which it won't find in that case.

Comment (jpowie01) [reply frontend/src/app/pages/marker-page/marker-page.component.ts]: Ohhh... Ok. So as I thought - Backend implementation is broken ;)

[This part](https://github.com/jpowie01/MedTagger/blob/master/backend/medtagger/api/scans/service_web_socket.py#L29-L32) should be rewritten to something like this:

```python
slices = list(business.get_slices_for_scan(scan_id, begin, count, orientation=orientation))
slices_to_send = list(reversed(slices)) if reversed_order else slices
last_in_batch = begin if reversed_order else begin + len(slices_to_send) - 1
for index, (_slice, image) in enumerate(slices_to_send):
    ...
```

BTW. I would like to refactor fetching images from Cassandra to use batch query in the future, so above code will probably change. For now, it'll be fine.
