### PR TITLE
Show tutorial only once and add user settings

### LINKED ISSUE #30: Allow user to skip the tutorial and/or display it only once
## Expected Behavior

User should be able to skip the tutorial and/or display tutorial only once.

## Actual Behavior

User should walk through the tutorial each time he/she wants to label scans.

## Steps to Reproduce the Problem

  1. Go to the labeling page.
  2. Go through the tutorial.
  3. Label scan.
  4. Go to the home page.
  5. Go to the labeling page.
  6. And... you still have to walk through the tutorial. Annoying.

### PR DESCRIPTION
**Pull request by piotrwalkusz1**
Fixes #30, #194

## Proposed Changes

  - user should see tutorial only once
  - add UserSettings table

### CODE REVIEW

File: frontend/src/app/pages/marker-tutorial-page/marker-tutorial-page.component.ts [hunk 1]
```diff
@@ -75,4 +82,11 @@ export class MarkerTutorialPageComponent implements OnInit {
         this.fourthStepVideo.nativeElement.play();
     }
 
+    endTutorial() {
```
Comment (Darkoon) [inline frontend/src/app/pages/marker-tutorial-page/marker-tutorial-page.component.ts]: Please add access modifier (even when its `public`) and return type.

File: backend/medtagger/api/users/service.py [hunk 2]
```diff
@@ -57,6 +57,23 @@ def get() -> Any:
...
+    """Set user's settings."""
+
+    @staticmethod
+    @login_required
+    @users_ns.doc(security='token')
+    def post(user_id: int) -> Any:
+        """Set current user's settings."""
+        user = get_current_user()
+        if user.id != user_id:
+            return {}, 403
```
Comment (jpowie01) [inline backend/medtagger/api/users/service.py]: Please add and raise an Exception for Access Forbidden to `exceptions.py` and add its handler in `api/__init__.py`. Pass some details why his access is forbidden - something like "Cannot update Settings for someone else."

File: backend/medtagger/database/models.py [hunk 3]
```diff
@@ -62,6 +63,19 @@ def role(self) -> Role:
         return self.roles[0]
 
 
+class UserSettings(Base):
+    """Settings of user."""
+
+    __tablename__ = 'UserSettings'
+    id: int = Column(Integer, autoincrement=True, primary_key=True)
```
Comment (jpowie01) [inline backend/medtagger/database/models.py]: Do not use separate values for `id` and `user_id`. This should be one field. Settings for given user should be stored under the same ID as owner's ID.

Look at this example: https://github.com/jpowie01/MedTagger/blob/backend_for_surveys/backend/medtagger/database/models.py#L368

File: backend/medtagger/repositories/users.py [hunk 4]
```diff
@@ -43,3 +43,9 @@ def set_user_info(user: User, firstName: str, lastName: str) -> None:
             user.first_name = firstName
             user.last_name = lastName
             session.add(user)
+
+    @staticmethod
+    def set_user_settings(settings: UserSettings) -> None:
```
Comment (jpowie01) [inline backend/medtagger/repositories/users.py]: I would allow users to update only one key at a time here. It won't be so common to update all Settings at once.

This function may be helpful: https://docs.python.org/3.6/library/functions.html#setattr

File: frontend/src/app/pages/settings-page/settings-page.component.html [hunk 5]
```diff
@@ -27,7 +27,7 @@
                         <input matInput placeholder="E-mail" type="text" [formControl]="userEmail" required readonly>
                         <mat-error *ngIf="userEmail.invalid">{{getUserEmailErrorMessage()}}</mat-error>
                     </mat-form-field>
-
+                    <mat-checkbox [formControl]="skipTutorial">Skip tutorial</mat-checkbox>
```
Comment (jpowie01) [inline frontend/src/app/pages/settings-page/settings-page.component.html]: I think it is not needed to have such checkbox in Settings page. Optionally we could make a separate accordeon section for operations like this but I don't think we've got time for this ;)

File: backend/medtagger/repositories/users.py [hunk 6]
```diff
@@ -1,6 +1,7 @@
 """Module responsible for definition of Users' Repository."""
 from typing import List, Optional
 
+from medtagger.api.utils import get_current_user
```
Comment (jpowie01) [inline backend/medtagger/repositories/users.py]: Repositories shouldn't use API namespace. These functions can be used outside of the API scope, eg. in Celery workers that won't have knowledge about logged in user ;)

File: backend/medtagger/repositories/users.py [hunk 7]
```diff
@@ -43,3 +44,11 @@ def set_user_info(user: User, firstName: str, lastName: str) -> None:
             user.first_name = firstName
             user.last_name = lastName
             session.add(user)
+
+    @staticmethod
+    def set_user_settings(name: str, value: object) -> None:
+        """Set user's settings parameter of specified name to provided value."""
+        with db_session() as session:
+            settings = get_current_user().settings
```
Comment (jpowie01) [inline backend/medtagger/repositories/users.py]: To overcome issue with using `get_current_user()`, please pass User object as an argument to this method.

File: backend/medtagger/repositories/users.py [hunk 8]
```diff
@@ -43,3 +44,11 @@ def set_user_info(user: User, firstName: str, lastName: str) -> None:
...
+            setattr(settings, name, value)
```
Comment (jpowie01) [inline backend/medtagger/repositories/users.py]: I've received an exception here :( User's Settings were empty - set to None.

screen shot 2018-05-11 at 21 09 00

File: backend/alembic/versions/6d69756a1476_add_user_settings.py [hunk 9]
```diff
@@ -0,0 +1,31 @@
...
+
+
+# revision identifiers, used by Alembic.
+revision = '6d69756a1476'
+down_revision = '729cd1e8cde1'
+branch_labels = None
+depends_on = None
+
+
+def upgrade():
```
Comment (jpowie01) [inline backend/alembic/versions/6d69756a1476_add_user_settings.py]: Apart of creating new table, we should also take care about existing users. What will happen to them?

I've applied your migration to my local environment where I had one user in the DB. Then, I've tried to skip my tutorial and... I got empty settings (set to None), so skipping failed :(

To overcome this issue, please create settings for each user that already exists in the database. To do so, you can use INSERT ... SELECT query. In case of troubles please contact with me or Karolina directly.

File: frontend/src/app/pages/marker-tutorial-page/marker-tutorial-page.component.ts [hunk 10]
```diff
@@ -75,4 +83,14 @@ export class MarkerTutorialPageComponent implements OnInit {
         this.fourthStepVideo.nativeElement.play();
     }
 
+    public endTutorial(): void {
+        this.user.settings.skipTutorial = true;
+        sessionStorage.setItem('userInfo', JSON.stringify(this.user));
+
+        let settings: UserSettings = new UserSettings();
+        settings.skipTutorial = true;
```
Comment (jpowie01) [inline frontend/src/app/pages/marker-tutorial-page/marker-tutorial-page.component.ts]: Please apply this value **after** you make sure that this field was saved on the backend side (next to line 93) :)
