### PR TITLE
Fix issues with slider being out of focus in Firefox.

### LINKED ISSUE #136: Slider is out of focus and cannot be used with keyboard arrows
## Expected Behavior

User should be able to use keyboard arrows any time he/she wants when navigating though slices.

## Actual Behavior

After new scan is loaded, user clicks somewhere on page or user create label, the slider becomes out of focus (but it is not grayed out) and user cannot use keyboard arrows to navigate. User needs to click on slider again to be able to navigate.

Browser version: Firefox Quantum (59.0.2 (64 bits))
Operating system: Ubuntu 16.04

## Steps to Reproduce the Problem

  1. Log in,
  2. Go to 'Labeling'
  3. Try to use arrows to navigate through scan.

### PR DESCRIPTION
**Pull request by jszemplinski**
Fixes #136 

## Proposed Changes

  - Users are now able to move between slices using keyboard arrows at any time, without slider losing focus.

### CODE REVIEW

File: frontend/src/app/components/scan-viewer/scan-viewer.component.ts [hunk 1]
```diff
@@ -71,7 +71,9 @@ export class ScanViewerComponent implements OnInit, AfterViewInit {
     }
 
     public sliderFocus() {
-        this.slider._elementRef.nativeElement.focus();
+        window.setTimeout(() => {
+            this.slider._elementRef.nativeElement.focus();
+        }, 10);
```
Comment (Darkoon) [inline frontend/src/app/components/scan-viewer/scan-viewer.component.ts]: Looks pretty hacky. How about that timeout value, why exacly `10` ?

File: frontend/src/app/components/scan-viewer/scan-viewer.component.ts [hunk 2]
```diff
@@ -71,7 +71,9 @@ export class ScanViewerComponent implements OnInit, AfterViewInit {
     }
 
     public sliderFocus() {
-        this.slider._elementRef.nativeElement.focus();
+        window.setTimeout(() => {
```
Comment (Darkoon) [inline frontend/src/app/components/scan-viewer/scan-viewer.component.ts]: It will be browser specific fix, so lets leave a comment here.

File: frontend/src/app/components/scan-viewer/scan-viewer.component.ts (hunk 1 above)
Comment (jszemplinski) [reply frontend/src/app/components/scan-viewer/scan-viewer.component.ts]: >Under IE, an element that is not visible cannot receive focus. Depending on the version of IE, it doesn't always re-render (or re-flow) the document until after the current JavaScript function has returned. This leads to all kinds of weird behavior, but mostly, you don't see visual updates during JavaScript code blocks. Combined with the inability to assign focus, that line was being silently ignored.

>Adding the setTimeout effectively gives control back to the browser, so it can reflow the document. Then, it immediately runs the timer function, and sets the focus. The 10ms timeout is enough, because the browser will take over even if there's a timer waiting.`

(quote from stackoverflow ;))

So, essentially, timeout length does not matter, what matters is solely the presence of timeout.
